### PR TITLE
replace bunyan-pretty with bunyan-prettystream, fixes #363

### PR DESCRIPTION
**Pull request by kefirchik**

### CODE REVIEW

**Comment by abhisheksoni27** [comment]
This pull request must be merged ASAP.

**Comment by spencern** [comment]
Might be worth leaving `bunyan-pretty` in for backwards compatability while adding `bunyan-prettystream`

**Comment by kefirchik** [comment]
`bunyan-pretty` has no source available, I think it is bad idea to use it at all :worried:

**Comment by spencern** [comment]
Agreed from a windows perspective, but it does have sources for linux/osx, so my concern is if anyone is currently using this repo then this will be a breaking change. I'm game either way, and agreed that in the long run, bunyan-pretty should be deprecated.

**Comment by aaronjudd** [comment]
@spencern yes it will be a breaking change, but we can update the package version to 2.4.0 which would mark this a non-backwards compatible release.  That should prevent older implementations from updating automatically.  We won't be in synch with the bunyan version but it will work.

**Comment by abhisheksoni27** [comment]
Finally.

**Comment by aaronjudd** [comment]
Finally indeed!

**Pull request merged**
